using System; using System.Diagnostics; using System.Drawing; using System.IO; using System.Text; using System.Windows.Forms;
class Tray : ApplicationContext {
  NotifyIcon icon; string engine;
  public Tray(){ engine=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DailyAgentDigest","daily-agent-digest.exe"); icon=new NotifyIcon{Icon=SystemIcons.Application,Visible=true,Text="Daily Agent Digest"}; var menu=new ContextMenuStrip(); menu.Items.Add("查看今日总结",null,(s,e)=>Run("state")); menu.Items.Add("生成今日总结",null,(s,e)=>Run("generate")); menu.Items.Add("设置",null,(s,e)=>Settings()); menu.Items.Add("退出",null,(s,e)=>Exit()); icon.ContextMenuStrip=menu; }
  void Run(string command,string input="{}"){ try { var p=new Process(); p.StartInfo.FileName=engine; p.StartInfo.Arguments="--app-command "+command; p.StartInfo.UseShellExecute=false; p.StartInfo.RedirectStandardInput=true; p.StartInfo.RedirectStandardOutput=true; p.Start(); p.StandardInput.Write(input); p.StandardInput.Close(); string json=p.StandardOutput.ReadToEnd(); p.WaitForExit(); MessageBox.Show(json,"Daily Agent Digest"); } catch(Exception x){ MessageBox.Show(x.Message,"Daily Agent Digest"); } }
  void Settings(){ using(var f=new Form{Text="日报设置",Width=420,Height=180}){ var u=new TextBox{Left=120,Top=20,Width=250,Text="https://api.deepseek.com/v1"}; var m=new TextBox{Left=120,Top=55,Width=250,Text="deepseek-flash"}; f.Controls.Add(new Label{Left=15,Top=23,Text="Base URL"}); f.Controls.Add(u); f.Controls.Add(new Label{Left=15,Top=58,Text="Model"}); f.Controls.Add(m); var b=new Button{Left=290,Top=95,Text="保存"}; b.Click+=(s,e)=>{ string esc= u.Text.Replace("\\","\\\\").Replace("\"","\\\""); string em= m.Text.Replace("\\","\\\\").Replace("\"","\\\""); Run("save-settings", "{\"base_url\":\""+esc+"\",\"model\":\""+em+"\"}"); f.Close(); }; f.Controls.Add(b); f.ShowDialog(); }}
  void Exit(){ icon.Visible=false; icon.Dispose(); Application.Exit(); }
  [STAThread] static void Main(){ bool created; using(var mutex=new System.Threading.Mutex(true,"DailyAgentDigest",out created)){ if(!created)return; Application.EnableVisualStyles(); Application.Run(new Tray()); }}
}
