#!/bin/bash
# Local development harness for Daily Agent Digest.
#
# Runs the engine and the macOS tray app from source against an isolated
# DIGEST_HOME under .dev/, so development never clobbers an installed copy.
# The isolated home is seeded with the installed app's .env once, so live LLM
# runs keep working without retyping the key.
#
# Usage: scripts/dev.sh <command> [options]
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
DEV=${DIGEST_DEV_HOME:-$REPO/.dev}
PROD_HOME=${DIGEST_PROD_HOME:-$HOME/.local/share/daily-agent-digest}
DEV_HOME=$DEV/home
DEV_MOCK_HOME=$DEV/mock-home
DEV_SOURCE=$DEV/source
DEV_LOGS=$DEV/logs
DEV_BIN=$DEV/bin
ENGINE_SRC=$REPO/daily_agent_digest.py
WRAPPER=$DEV_BIN/dev-engine
APP_OUT="$DEV/app/Daily Agent Digest Dev.app"
APP_BIN="$APP_OUT/Contents/MacOS/DailyAgentDigest"
APP_ID=com.daily-agent-digest.tray.dev
MOCK_PORT=${DIGEST_DEV_MOCK_PORT:-8765}
MOCK_PID_FILE=$DEV/mock-llm.pid
APP_PID_FILE=$DEV/app.pid
PYTHON=${PYTHON:-python3}
DEFAULT_DATE=$("$PYTHON" -c 'import datetime as d;print(d.datetime.now(d.timezone(d.timedelta(hours=8))).date().isoformat())')

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

guard() {
  case "$DEV_HOME" in
    "$REPO"/*) ;;
    *) die "refusing to run: dev home $DEV_HOME is not under $REPO" ;;
  esac
  [ "$DEV_HOME" != "$PROD_HOME" ] || die "refusing to run: dev home equals the installed app home"
  [ "$DEV" != "$PROD_HOME" ] || die "refusing to run: dev root equals the installed app home"
}

git_sha() { git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown; }

ensure_setup() {
  guard
  mkdir -p "$DEV_HOME" "$DEV_SOURCE" "$DEV_LOGS" "$DEV_BIN" "$DEV/app"
  if [ ! -f "$DEV_HOME/.env" ]; then
    if [ -f "$PROD_HOME/.env" ]; then
      cp "$PROD_HOME/.env" "$DEV_HOME/.env"
      chmod 600 "$DEV_HOME/.env"
      say "dev .env seeded from $PROD_HOME/.env (mode 600); edit it freely, the installed copy is untouched"
    else
      umask 077
      printf 'LLM_BASE_URL="https://api.deepseek.com/v1"\nLLM_MODEL="deepseek-flash"\nLLM_API_KEY=""\n' > "$DEV_HOME/.env"
      chmod 600 "$DEV_HOME/.env"
      say "created an empty dev .env at $DEV_HOME/.env (use 'generate' without --live to run offline)"
    fi
  fi
  cat > "$WRAPPER" <<EOF
#!/bin/sh
# Generated by scripts/dev.sh - runs the engine from source against the dev home.
export DIGEST_HOME="\${DIGEST_HOME:-$DEV_HOME}"
export DIGEST_SOURCE_ROOT="\${DIGEST_SOURCE_ROOT:-$DEV_SOURCE}"
export DIGEST_OUTPUT_DIR="\${DIGEST_OUTPUT_DIR:-$DEV_HOME}"
# 运行时解析版本号,这样「关于」里的引擎版本不会随提交而过期。
DIGEST_SHA=\$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)
export DIGEST_RELEASE_VERSION="\${DIGEST_RELEASE_VERSION:-dev-\$DIGEST_SHA}"
export DIGEST_DEBUG="\${DIGEST_DEBUG:-1}"
exec "$PYTHON" "$ENGINE_SRC" "\$@"
EOF
  chmod 755 "$WRAPPER"
  if [ ! -d "$DEV_SOURCE/.codex" ] || [ ! -d "$DEV_SOURCE/.pi" ] || [ ! -d "$DEV_SOURCE/.dsh" ]; then
    "$PYTHON" "$REPO/scripts/dev_fixtures.py" "$DEV_SOURCE" --date "$DEFAULT_DATE"
  fi
}

ensure_mock_home() {
  guard
  mkdir -p "$DEV_MOCK_HOME"
  umask 077
  cat > "$DEV_MOCK_HOME/.env" <<EOF
LLM_BASE_URL="http://127.0.0.1:$MOCK_PORT/v1"
LLM_MODEL="dev-mock"
LLM_API_KEY="mock-dev-key"
DIGEST_MEMBER="本地开发者"
EOF
  chmod 600 "$DEV_MOCK_HOME/.env"
}

# ---------------------------------------------------------------- mock LLM ---
start_mock() {
  local mode=${1:-ok}
  stop_mock
  nohup "$PYTHON" "$REPO/scripts/dev_mock_llm.py" --port "$MOCK_PORT" --mode "$mode" \
    >"$DEV_LOGS/mock-llm.log" 2>&1 &
  echo $! > "$MOCK_PID_FILE"
  disown 2>/dev/null || true
  local i
  for i in $(seq 1 50); do
    if curl -fsS "http://127.0.0.1:$MOCK_PORT/health" >/dev/null 2>&1; then
      say "mock LLM ready: http://127.0.0.1:$MOCK_PORT/v1 (mode=$mode)"
      return 0
    fi
    sleep 0.1
  done
  tail -5 "$DEV_LOGS/mock-llm.log" >&2 || true
  die "mock LLM did not become ready"
}

stop_mock() {
  if [ -f "$MOCK_PID_FILE" ]; then
    kill "$(cat "$MOCK_PID_FILE")" 2>/dev/null || true
    rm -f "$MOCK_PID_FILE"
  fi
  pkill -f "dev_mock_llm.py --port $MOCK_PORT" 2>/dev/null || true
}

# ------------------------------------------------------------------- engine ---
print_state() {
  "$PYTHON" - "$1" "$2" <<'PY'
import json, pathlib, sys
home, label = sys.argv[1], sys.argv[2]
path = pathlib.Path(home) / "state.json"
if not path.exists():
    print(f"{label}: no state.json yet at {path}")
    raise SystemExit(0)
try:
    state = json.loads(path.read_text(encoding="utf-8"))
except json.JSONDecodeError as exc:
    print(f"{label}: state.json is not valid JSON: {exc}")
    raise SystemExit(0)
items = state.get("work_items") or []
print(f"{label}: {path}")
print(f"  date           : {state.get('date')}")
print(f"  report_status  : {state.get('report_status')}")
print(f"  release_version: {state.get('release_version')}")
print(f"  generated_at   : {state.get('generated_at')}")
print(f"  last_error     : {state.get('last_error')}")
print(f"  work_items     : {len(items)}  (计入上报 {state.get('included_count')} / 已排除 {state.get('excluded_count')})")
for item in items:
    flag = "excluded" if item.get("excluded") else "included"
    desc = item.get("desc") or ""
    print(f"    - [{flag}] {item.get('title')}  ({len(desc)} 字)")
    print(f"        {desc[:100]}{'…' if len(desc) > 100 else ''}")
PY
}

cmd_generate() {
  local live=0 mode=ok date=$DEFAULT_DATE home source
  while [ $# -gt 0 ]; do
    case "$1" in
      --live) live=1 ;;
      --mock) live=0 ;;
      --real) source=$HOME ;;
      --mode=*) mode=${1#--mode=} ;;
      --date=*) date=${1#--date=} ;;
      *) die "unknown option for generate: $1" ;;
    esac
    shift
  done
  ensure_setup
  source=${source:-$DEV_SOURCE}
  if [ "$live" = 1 ]; then
    home=$DEV_HOME
    say "generating against the LIVE endpoint from $DEV_HOME/.env"
  else
    ensure_mock_home
    start_mock "$mode"
    home=$DEV_MOCK_HOME
  fi
  printf '{"date":"%s","source_root":"%s"}' "$date" "$source" | DIGEST_HOME="$home" "$WRAPPER" --app-command clear >/dev/null
  printf '{"date":"%s","source_root":"%s"}' "$date" "$source" | DIGEST_HOME="$home" "$WRAPPER" --app-command generate >/dev/null
  [ "$live" = 1 ] || stop_mock
  print_state "$home" "dev state"
}

cmd_cmd() {
  local name=${1:-} want_mock=0
  [ -n "$name" ] || die "usage: dev.sh cmd <command> [json] [--mock]"
  shift
  local payload='{}'
  if [ $# -gt 0 ] && [ "${1#--}" = "$1" ]; then payload=$1; shift; fi
  while [ $# -gt 0 ]; do
    case "$1" in
      --mock) want_mock=1 ;;
      *) die "unknown option for cmd: $1" ;;
    esac
    shift
  done
  ensure_setup
  local home=$DEV_HOME
  if [ "$want_mock" = 1 ]; then ensure_mock_home; home=$DEV_MOCK_HOME; fi
  printf '%s' "$payload" | DIGEST_HOME="$home" "$WRAPPER" --app-command "$name" | "$PYTHON" -m json.tool
}

cmd_run() {
  ensure_setup
  local date=$DEFAULT_DATE
  while [ $# -gt 0 ]; do
    case "$1" in
      --date=*) date=${1#--date=} ;;
      --date) shift; date=${1:?} ;;
      *) die "unknown option for run: $1" ;;
    esac
    shift
  done
  DIGEST_HOME="$DEV_HOME" "$WRAPPER" --date "$date" --root "$DEV_SOURCE" --out "$DEV_HOME/$date.json"
  say "wrote $DEV_HOME/$date.json"
}

# ---------------------------------------------------------------------- app ---
cmd_build() {
  ensure_setup
  local sha
  sha=$(git_sha)
  DIGEST_RELEASE_VERSION="dev-$sha" DIGEST_UI_BUILD_ID="dev-$sha" DIGEST_APP_ID="$APP_ID" \
    bash "$REPO/native/macos/build.sh" "$APP_OUT"
  say "built $APP_OUT (dev-$sha, $APP_ID)"
}

stop_app() {
  if [ -f "$APP_PID_FILE" ]; then
    kill "$(cat "$APP_PID_FILE")" 2>/dev/null || true
    rm -f "$APP_PID_FILE"
  fi
  # Exact dev bundle path only; never a broad pattern that could hit another app.
  pkill -f "$APP_BIN" 2>/dev/null || true
}

cmd_app() {
  local demo=0 source=$DEV_SOURCE
  while [ $# -gt 0 ]; do
    case "$1" in
      --demo) demo=1 ;;
      --real) source=$HOME ;;
      *) die "unknown option for app: $1" ;;
    esac
    shift
  done
  ensure_setup
  if [ ! -x "$APP_BIN" ] || [ "$REPO/native/macos/DailyAgentDigest.swift" -nt "$APP_BIN" ] || [ "$REPO/native/macos/build.sh" -nt "$APP_BIN" ]; then
    cmd_build
  fi
  stop_app
  local home=$DEV_HOME autogen=0
  if [ "$demo" = 1 ]; then
    # Demo mode drives the whole generation dialog against the offline mock, so
    # the progress -> result flow and the state mapping can be watched locally.
    ensure_mock_home
    start_mock ok
    home=$DEV_MOCK_HOME
    autogen=1
    say "demo mode: mock LLM on port $MOCK_PORT, home=$home, auto-generating once"
  fi
  (
    export DIGEST_ENGINE="$WRAPPER"
    export DIGEST_HOME="$home"
    export DIGEST_SOURCE_ROOT="$source"
    export DIGEST_DEBUG=1
    export DIGEST_DEBUG_LOG="$DEV_LOGS/tray.debug.log"
    [ "$autogen" = 1 ] && export DIGEST_DEBUG_AUTOGENERATE=1
    nohup "$APP_BIN" >"$DEV_LOGS/tray.out.log" 2>&1 &
    echo $! > "$APP_PID_FILE"
    disown 2>/dev/null || true
  )
  sleep 1
  if pgrep -f "$APP_BIN" >/dev/null 2>&1; then
    say "dev tray running (pid $(cat "$APP_PID_FILE"))"
    say "menu bar: 查看今日总结 / 生成今日总结 / 设置 / 退出"
    say "engine  : $WRAPPER -> $ENGINE_SRC"
    say "home    : $home"
    say "source  : $source$([ "$source" = "$DEV_SOURCE" ] && echo " (fixtures)")"
    say "logs    : $DEV_LOGS/tray.debug.log"
  else
    tail -20 "$DEV_LOGS/tray.out.log" >&2 || true
    die "dev tray failed to start"
  fi
}

cmd_status() {
  guard
  say "repo            : $REPO ($(git_sha))"
  say "dev root        : $DEV"
  say "dev home        : $DEV_HOME $([ -f "$DEV_HOME/.env" ] && echo '(env ready)' || echo '(not set up)')"
  say "mock home       : $DEV_MOCK_HOME $([ -f "$DEV_MOCK_HOME/.env" ] && echo '(env ready)')"
  say "fixture source  : $DEV_SOURCE $([ -d "$DEV_SOURCE/.codex" ] && echo '(fixtures ready)' || echo '(missing)')"
  if pgrep -f "$APP_BIN" >/dev/null 2>&1; then
    say "dev tray        : running (pid $(pgrep -f "$APP_BIN" | tr '\n' ' '))"
  else
    say "dev tray        : stopped"
  fi
  if curl -fsS "http://127.0.0.1:$MOCK_PORT/health" >/dev/null 2>&1; then
    say "mock LLM        : running on port $MOCK_PORT"
  else
    say "mock LLM        : stopped"
  fi
  if pgrep -f "$PROD_HOME/.*app/Contents/MacOS/DailyAgentDigest" >/dev/null 2>&1; then
    say "installed tray  : RUNNING (this will fight the dev build for the menu bar)"
  else
    say "installed tray  : stopped"
  fi
  say "installed files : $PROD_HOME (preserved, not modified by this harness)"
}

cmd_logs() {
  for f in "$DEV_LOGS/tray.debug.log" "$DEV_LOGS/tray.out.log" "$DEV_LOGS/mock-llm.log" "$DEV_HOME/debug.log"; do
    [ -f "$f" ] || continue
    say "=== $f ==="
    tail -n 25 "$f"
  done
}

cmd_clean() {
  stop_app
  stop_mock
  case "$DEV" in
    "$REPO"/.dev*) rm -rf "$DEV" && say "removed $DEV" ;;
    *) die "refusing to remove $DEV" ;;
  esac
}

usage() {
  cat <<'USAGE'
Local development harness for Daily Agent Digest.

  scripts/dev.sh setup                 prepare .dev/ (isolated home, .env, fixtures, engine wrapper)
  scripts/dev.sh test                  run the Python unit tests
  scripts/dev.sh generate [options]    clear + generate + print the resulting state
                                         (default: offline mock LLM; --live uses .env endpoint)
                                         --real  read the real $HOME instead of fixtures
                                         --mode=ok|malformed|error500|hang   mock failure injection
                                         --date=YYYY-MM-DD
  scripts/dev.sh run [--date=D]        run the engine CLI (read-only report file)
  scripts/dev.sh cmd <name> [json] [--mock]
                                       call an app-command: settings|save-settings|clear|generate|
                                       state|exclude|restore|submit|tick
  scripts/dev.sh build                 build the dev tray app bundle
  scripts/dev.sh app [--demo]         build if needed, then launch the dev tray app
                                         --demo: run against the mock LLM and auto-generate once
                                                 so the progress -> result dialog can be watched
                                         --real: collect from the real $HOME instead of fixtures
  scripts/dev.sh state [--mock]        pretty-print the dev state.json
  scripts/dev.sh stop                  stop the dev tray app and the mock LLM
  scripts/dev.sh status                show what is running and where the dev state lives
  scripts/dev.sh logs                  tail dev logs
  scripts/dev.sh clean                 stop everything and delete .dev/
USAGE
}

main() {
  local command=${1:-}
  [ $# -gt 0 ] && shift
  case "$command" in
    setup) ensure_setup; ensure_mock_home; cmd_status ;;
    fixtures) ensure_setup; "$PYTHON" "$REPO/scripts/dev_fixtures.py" "$DEV_SOURCE" "$@" ;;
    test) exec "$PYTHON" -m unittest discover -s "$REPO/tests" -v ;;
    run) cmd_run "$@" ;;
    generate) cmd_generate "$@" ;;
    cmd) cmd_cmd "$@" ;;
    build) cmd_build ;;
    app) cmd_app "$@" ;;
    state)
      home=$DEV_HOME
      [ "${1:-}" = "--mock" ] && home=$DEV_MOCK_HOME
      print_state "$home" "dev state" ;;
    stop) stop_app; stop_mock; say "dev stopped" ;;
    status) cmd_status ;;
    logs) cmd_logs ;;
    clean) cmd_clean ;;
    ""|-h|--help|help) usage ;;
    *) usage; die "unknown command: $command" ;;
  esac
}

main "$@"
